In [55]:
import numpy as np
import matplotlib as plt
import math

In [62]:
arr = np.loadtxt("out.txt")

In [63]:
def ans(t, x, y):
    return math.exp(-2 * t * math.pi ** 2 ) * math.sin(math.pi * x) * math.sin(math.pi * y)

In [64]:
arr_new = np.zeros(arr.shape)

In [80]:
for i in range(10):
    for j in range(100):
        arr_new[i][j] = ans(i / 10., (j % 10) / 9., (j // 10) / 9.)  

In [77]:
i = 1
arr_new[i][11] - arr[i][11]

-0.02655064683766071

In [78]:
arr_new[1][11]

0.013049353162339294

In [79]:
arr[1][11]

0.0396

In [72]:
arr[1]

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.0396  ,
       0.074424, 0.100272, 0.114025, 0.114025, 0.100272, 0.074424,
       0.0396  , 0.      , 0.      , 0.074424, 0.139872, 0.188449,
       0.214296, 0.214296, 0.188449, 0.139872, 0.074424, 0.      ,
       0.      , 0.100272, 0.188449, 0.253897, 0.28872 , 0.28872 ,
       0.253897, 0.188449, 0.100272, 0.      , 0.      , 0.114025,
       0.214296, 0.28872 , 0.328321, 0.328321, 0.28872 , 0.214296,
       0.114025, 0.      , 0.      , 0.114025, 0.214296, 0.28872 ,
       0.328321, 0.328321, 0.28872 , 0.214296, 0.114025, 0.      ,
       0.      , 0.100272, 0.188449, 0.253897, 0.28872 , 0.28872 ,
       0.253897, 0.188449, 0.100272, 0.      , 0.      , 0.074424,
       0.139872, 0.188449, 0.214296, 0.214296, 0.188449, 0.139872,
       0.074424, 0.      , 0.      , 0.0396  , 0.074424, 0.100272,
       0.114025, 0.114025, 0.100272, 0.074424, 0.0396  , 0.   

In [68]:
arr[i]

array([0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00,
       0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 6.00e-05,
       1.12e-04, 1.51e-04, 1.72e-04, 1.72e-04, 1.51e-04, 1.12e-04,
       6.00e-05, 0.00e+00, 0.00e+00, 1.12e-04, 2.11e-04, 2.84e-04,
       3.23e-04, 3.23e-04, 2.84e-04, 2.11e-04, 1.12e-04, 0.00e+00,
       0.00e+00, 1.51e-04, 2.84e-04, 3.82e-04, 4.35e-04, 4.35e-04,
       3.82e-04, 2.84e-04, 1.51e-04, 0.00e+00, 0.00e+00, 1.72e-04,
       3.23e-04, 4.35e-04, 4.94e-04, 4.94e-04, 4.35e-04, 3.23e-04,
       1.72e-04, 0.00e+00, 0.00e+00, 1.72e-04, 3.23e-04, 4.35e-04,
       4.94e-04, 4.94e-04, 4.35e-04, 3.23e-04, 1.72e-04, 0.00e+00,
       0.00e+00, 1.51e-04, 2.84e-04, 3.82e-04, 4.35e-04, 4.35e-04,
       3.82e-04, 2.84e-04, 1.51e-04, 0.00e+00, 0.00e+00, 1.12e-04,
       2.11e-04, 2.84e-04, 3.23e-04, 3.23e-04, 2.84e-04, 2.11e-04,
       1.12e-04, 0.00e+00, 0.00e+00, 6.00e-05, 1.12e-04, 1.51e-04,
       1.72e-04, 1.72e-04, 1.51e-04, 1.12e-04, 6.00e-05, 0.00e

In [34]:
arr

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.21559489e-07,
        -3.10392954e-07, -1.32726024e-07, -8.88334651e-08,
        -8.88334651e-08, -1.32726024e-07, -3.10392954e-07,
         2.21559489e-07, -4.18853874e-17,  0.00000000e+00,
        -3.10392954e-07,  8.88334653e-08, -3.99226419e-07,
        -2.21559489e-07, -2.21559489e-07, -3.99226419e-07,
         8.88334651e-08, -3.10392954e-07, -7.87187789e-17,
         0.00000000e+00, -1.32726024e-07, -3.99226419e-07,
         1.11022302e-16,  4.68047557e-07,  4.68047557e-07,
         0.00000000e+00, -3.99226419e-07, -1.32726024e-07,
        -1.06057524e-16,  0.00000000e+00, -8.88334651e-08,
        -2.21559489e-07,  4.68047557e-07, -3.10392954e-07,
        -3.10392954e-07,  4.68047557e-07, -2.21559489e-07,
        -8.88334653e-08, -1.20604166e-16,  0.00000000e+0

In [109]:
from math import sin, pi
h_x = 0.25

5 / (8 * 16 * sin(pi * h_x * 0.5)**2 + 1 / 0.2)

0.21056917433825845

In [90]:
def sinfun(x, y):
    return 0.21056917433825845 * sin(pi * x) * sin(pi * y)

In [93]:
sinfun(0.75, 0.25)

0.10528458716912922

In [25]:
1 / 9.

0.1111111111111111

In [110]:
tau = 0.2

disc = 1 / (8 * 16 * sin(math.pi / 8) ** 2  + 1 / tau) 

In [113]:
disc * 5 * disc * 5

0.04433937718149588

In [115]:
math.exp( - 2 * 0.2 * math.pi **2 * 2)

0.00037234730603371473